# Production environment values
image:
  tag: "prod-tag"
  registry: "prod.acr.name"
azure:
  keyVaultName: "prod.keyvault.name"
  tenantId: "prod-tenant-id"
  workloadIdentityClientId: "prod-client-id"
replicaCount: 3
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
ingress:
  host: "prod.example.com"
