apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet.name" . }}
  labels:
    {{ include "dotnet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "dotnet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "dotnet.labels" . | nindent 8 }}
      annotations:
        azure.workload.identity/client-id: {{ .Values.azure.workloadIdentityClientId }}
    spec:
      serviceAccountName: electric-equipment-sa
      containers:
      - name: {{ include "dotnet.name" . }}
        image: {{ include "dotnet.image" . }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 5
